/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopprojectversion2;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class singInFrame extends javax.swing.JFrame {

    /**
     * Creates new form loginForgotFrame
     */
    public singInFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        confPassword = new javax.swing.JTextField();
        userName = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        secret = new javax.swing.JTextField();
        newPassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        phoneNo = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        loginPassword2 = new javax.swing.JTextField();
        loginUserName2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Re enter password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 70, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mail address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 90, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Secret");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 40, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("New password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        getContentPane().add(confPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 130, -1));
        getContentPane().add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 130, -1));
        getContentPane().add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 130, -1));
        getContentPane().add(secret, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 130, -1));
        getContentPane().add(newPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 130, -1));

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone No");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 70, -1));
        getContentPane().add(phoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 130, -1));

        jButton3.setText("Log in");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Admin password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel9.setText("Admin username");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel1.add(loginPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 110, -1));
        jPanel1.add(loginUserName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 230, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Gamitha\\kiu\\2nd sem 2024.08.26\\oop\\project\\final project version 2\\images\\dashboard.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 580, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String Vname = userName.getText();
        String Vno = phoneNo.getText();
        String Vnic = mail.getText();
        String Vsallery = secret.getText();
        
        String abc ="0";
        
        if(abc == "1"){
        try{
            Statement s = db.mycon().createStatement();
            s.executeUpdate("INSERT INTO employees (name,contactNo,nic,sallery) VALUES ('"+Vname+"','"+Vno+"','"+Vnic+"','"+Vsallery+"')");
            
        }
        catch(Exception e){
            System.out.println(e);
        }
        }
        
        
        
        if(abc == "0"){
            System.out.println("inside the if");
        String dbPassword ="";
        String dbuserName ="";
        try{
            Statement s = db.mycon().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM logins WHERE userName = '"+loginUserName2.getText()+"'");
            
            if(rs.next()){
                dbPassword=(rs.getString("password"));
                dbuserName=(rs.getString("userName"));
            }
            
        }
        catch(SQLException e){
            System.out.println(e);
        }
        
        
        if(loginPassword2.getText().equals("")&&loginUserName2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter admin details");
        }
        else if(loginPassword2.getText().equals(dbPassword)&&loginUserName2.getText().equals(dbuserName))
        {
            String aVname = userName.getText();
            String aVno = phoneNo.getText();
            String aVmail = mail.getText();
            String aVsecret = secret.getText();
            String aVconfPassword = confPassword.getText();
            if(userName.getText().equals("")||phoneNo.getText().equals("")||mail.getText().equals("")||secret.getText().equals("")||confPassword.getText().equals("")||newPassword.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please enter new account details");
            }
            
            else if(newPassword.getText().equals(confPassword.getText())){
            try{
                Statement s = db.mycon().createStatement();
                s.executeUpdate("INSERT INTO logins (userName,password,phoneNO,mailAddress,secret,adminUserName,createDateTime) VALUES ('"+aVname+"','"+aVno+"','"+aVmail+"','"+aVsecret+"','"+aVconfPassword+"','"+aVconfPassword+"')");
                userName.setText("");
                phoneNo.setText("");
                mail.setText("");
                secret.setText("");
                confPassword.setText("");
                System.out.println("try");
            }
            catch(Exception e){
                System.out.println(e);
                System.out.println("catch");
            }
            
            
            JOptionPane.showMessageDialog(null, "Account create successfully");
            }
            else{
               JOptionPane.showMessageDialog(null, "Please check the passwords"); 
            }
        }
        else
        {
           //JOptionPane.showConfirmDialog(null, "Error");
            JOptionPane.showMessageDialog(null, "Invalid admin details");
        }}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        loginFrame login = new loginFrame();
            login.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(singInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(singInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(singInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(singInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new singInFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField loginPassword2;
    private javax.swing.JTextField loginUserName2;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField newPassword;
    private javax.swing.JTextField phoneNo;
    private javax.swing.JTextField secret;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
